const fs = require('fs');
const path = require('path');

// Calculate absolute path to UI directory dynamically so it runs anywhere
// Priority: 1) UI_PROJECT_DIR env variable, 2) auto-detect app/*/src, 3) fallback path
function findUiProjectDir() {
  // Check environment variable first
  if (process.env.UI_PROJECT_DIR) {
    const envPath = path.resolve(process.env.UI_PROJECT_DIR);
    if (fs.existsSync(envPath)) {
      return envPath;
    }
  }

  // Auto-detect: find app/*/src directory
  const appDir = path.resolve(__dirname, '../../../app');
  if (fs.existsSync(appDir)) {
    const entries = fs.readdirSync(appDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        const srcDir = path.join(appDir, entry.name, 'src');
        const localesDir = path.join(srcDir, 'locales');
        if (fs.existsSync(localesDir)) {
          return path.join(appDir, entry.name);
        }
      }
    }
  }

  // Fallback: relative path from script location
  return path.resolve(__dirname, '../../../app/cnma_ai_agent_extraction_ui');
}

const uiDir = findUiProjectDir();
const srcDir = path.join(uiDir, 'src');
const enJsonPath = path.join(srcDir, 'locales', 'en.json');
const tasksDir = path.join(uiDir, 'tasks');
const mdPath = path.join(tasksDir, 'missing-translation-tasks.md');

if (!fs.existsSync(tasksDir)) {
    fs.mkdirSync(tasksDir, { recursive: true });
}

// Ensure the locale file exists
if (!fs.existsSync(enJsonPath)) {
    console.error(`❌ Translation file not found at: ${enJsonPath}`);
    console.error(`   Set UI_PROJECT_DIR environment variable to specify the project path.`);
    console.error(`   Or ensure your UI project has the structure: app/<project-name>/src/locales/en.json`);
    process.exit(1);
}

// Flattens complex JSON keys to dotted strings
function flattenKeys(obj, prefix = '') {
  const keys = new Set();
  for (const [key, value] of Object.entries(obj)) {
    const newPrefix = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      const nestedKeys = flattenKeys(value, newPrefix);
      for (const nestedKey of nestedKeys) {
        keys.add(nestedKey);
      }
    } else {
      keys.add(newPrefix);
    }
  }
  return keys;
}

const enJson = JSON.parse(fs.readFileSync(enJsonPath, 'utf8'));
const validKeys = flattenKeys(enJson);

function getAllFiles(dirPath, arrayOfFiles) {
  const files = fs.readdirSync(dirPath);
  files.forEach(function(file) {
    const fullPath = path.join(dirPath, file);
    if (fs.statSync(fullPath).isDirectory()) {
      arrayOfFiles = getAllFiles(fullPath, arrayOfFiles);
    } else {
      if (file.endsWith('.ts') || file.endsWith('.tsx')) {
        arrayOfFiles.push(fullPath);
      }
    }
  });
  return arrayOfFiles;
}

const filesToScan = getAllFiles(srcDir, []);
const tRegex = /\bt\(\s*['"]([^'"]+)['"]/g;
const i18nKeyRegex = /\bi18nKey=\s*['"]([^'"]+)['"]/g;

const missingKeysMap = new Map();

for (const file of filesToScan) {
  const content = fs.readFileSync(file, 'utf8');
  let match;
  
  const extractAndCheck = (regex) => {
      while ((match = regex.exec(content)) !== null) {
        const key = match[1];
        if (key.includes('${')) continue;
        if (!validKeys.has(key)) {
          if (!missingKeysMap.has(key)) {
            missingKeysMap.set(key, new Set());
          }
          missingKeysMap.get(key).add(path.relative(uiDir, file));
        }
      }
  };

  extractAndCheck(tRegex);
  extractAndCheck(i18nKeyRegex);
}

if (missingKeysMap.size === 0) {
    console.log('✅ All translation keys used in the code are present in en.json.');
    process.exit(0);
}

// Auto-fix dictionary and generate task MD
let mdContent = '# Missing Translation Keys Auto-Fixed\n\n';
mdContent += 'This file was auto-generated by `.agent/workflows/scripts/fix_missing_translations.cjs`.\n\n';
mdContent += 'All listed keys have been automatically injected into `en.json` with generated fallback strings.\n\n';

function setDeep(obj, pathStr, value) {
  const keys = pathStr.split('.');
  let current = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    const key = keys[i];
    if (!current[key] || typeof current[key] !== 'object') {
      current[key] = {};
    }
    current = current[key];
  }
  const lastKey = keys[keys.length - 1];
  if (current[lastKey] === undefined) {
    current[lastKey] = value;
    return true;
  }
  return false;
}

function generateDefaultText(keyStr) {
   const parts = keyStr.split('.');
   const lastPart = parts[parts.length - 1];
   let text = lastPart
      .replace(/([a-z])([A-Z])/g, '$1 $2')
      .replace(/_/g, ' ')
      .replace(/^./, str => str.toUpperCase());
   
   text = text.replace(/\bId\b/g, 'ID');
   text = text.replace(/\bAi\b/ig, 'AI');
   text = text.replace(/\bCsv\b/ig, 'CSV');
   text = text.replace(/\bPdf\b/ig, 'PDF');
   text = text.replace(/\bDesc\b/ig, 'Description');
   
   return text;
}

let added = 0;
for (const [key, files] of missingKeysMap.entries()) {
    const defaultText = generateDefaultText(key);
    if (setDeep(enJson, key, defaultText)) {
        added++;
        // Track the successfully generated fallback in the markdown log
        mdContent += `- [x] \`${key}\` -> **"${defaultText}"** (found in: ${Array.from(files).join(', ')})\n`;
    }
}

// Deeply sort the resulting JSON to maintain localization standards
function sortObject(obj) {
    if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) {
        return obj;
    }
    const sorted = {};
    Object.keys(obj).sort().forEach(key => {
        sorted[key] = sortObject(obj[key]);
    });
    return sorted;
}

const sortedEnJson = sortObject(enJson);
fs.writeFileSync(enJsonPath, JSON.stringify(sortedEnJson, null, 4));
fs.writeFileSync(mdPath, mdContent, 'utf8');

console.log(`✅ Auto-filled ${added} missing keys into en.json!`);
console.log(`✅ Generated tasks report at: ${path.relative(process.cwd(), mdPath)}`);
